version: '3.8'

services:
  db:
    image: postgres:13
    container_name: histograms-kata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: commodities
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
